### ISSUE TITLE
libfmt patch

### ISSUE THREAD

**Issue by azihassan** [azihassan/devilutionX#8]
To get the game to compile, I had to patch the libfmt source code to add [this line](https://github.com/azihassan/devilutionX/blob/dreamcast/libfmt-long-double.patch). A cleaner approach should be used for this.

**Comment by glebm** [comment]
What was the compilation error? That struct in libfmt is for extended precision support, which is optional and shouldn't cause an error even if not supported.

**Comment by azihassan** [comment]
Thanks! It's been a while so I don't remember the specifics, but here's a reproduction: https://github.com/azihassan/devilutionX/actions/runs/11171993466/job/31057721326

**Comment by azihassan** [comment]
Looks like it's possible to disable double support in libfmt by setting a FMT_USE_DOUBLE macro to 0. I'll look into how to do it with cmake

**Comment by glebm** [comment]
Here is an example https://github.com/diasurgical/devilutionX/blob/1a32a705fe230932046e6c1c8058af3121ae3e6f/3rdParty/libfmt/CMakeLists.txt#L25

**Comment by azihassan** [comment]
That helps thanks! After [a lot](https://github.com/azihassan/devilutionX/commits/fix/ISSUE-8-libfmt-patch/) of trial and error, I discovered that [those flags aren't supported anymore](https://github.com/fmtlib/fmt/issues/4175#issuecomment-2369036658). The proposed alternative didn't have a noticeable performance impact on Flycast, but it did require that I bump libfmt to last week's commit which might break compilation for the other platforms. I'll let github actions test that possibility

**Comment by glebm** [comment]
Looks like `FMT_BUILTIN_TYPES=0` should work instead (with the latest libfmt).
We've recently removed all the usages of `double` from DevilutionX (didn't really need it).

**Comment by azihassan** [comment]
Agreed, that's the proposed alternative I mentioned having tested on Flycast. Not on console yet though

> By the way we've recently removed all the usages of double from DevilutionX (didn't really need it).

Nice, I updated the fork to fetch those changes
